-- DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS orders;

-- CREATE TABLE user (
--   id INTEGER PRIMARY KEY AUTOINCREMENT,
--   username TEXT UNIQUE NOT NULL,
--   password TEXT NOT NULL
-- );

CREATE TABLE orders (
    id INTEGER PRIMARY KEY,
    item TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    price REAL NOT NULL,
    status TEXT NOT NULL
);
